model:
  # Network architecture
  encoder:
    input_size: 256
    hidden_sizes: [512, 1024]
    num_layers: 3
    dropout: 0.3
    activation: "relu"
    normalization: "layer"
    residual: true
    
  decoder:
    hidden_sizes: [1024, 512, 256]
    num_layers: 3
    dropout: 0.3
    activation: "relu"
    normalization: "layer"
    residual: true
    output_activation: "sigmoid"
    
  attention:
    num_heads: 8
    dropout: 0.1
    key_dim: 64
    value_dim: 64
    positional_encoding: true
    max_position: 1024
    
  # Training parameters
  training:
    batch_size: 32
    learning_rate: 0.001
    num_epochs: 100
    early_stopping_patience: 10
    optimizer: "adam"
    lr_scheduler:
      type: "reduce_on_plateau"
      patience: 5
      factor: 0.5
    weight_decay: 0.0001
    gradient_clipping: 1.0
    mixed_precision: true
    
  # Recovery strategies
  recovery_strategies:
    - name: "bitcoin_core_2010"
      version_range: [0.1, 0.3.24]
      priority: 1
    - name: "bitcoin_core_2011"
      version_range: [0.4.0, 0.8.6]
      priority: 2
    - name: "berkeley_db"
      db_versions: ["4.8", "5.1", "5.3"]
      priority: 3
    - name: "encrypted_key"
      encryption_types: ["aes-256-cbc", "chacha20-poly1305"]
      priority: 4
    
  # Thresholds
  thresholds:
    strategy_confidence: 0.8
    entropy_threshold: 7.5
    pattern_match_threshold: 0.9
    minimum_key_length: 32
    maximum_attempts: 1000
    timeout_seconds: 3600
    
  # Feature extraction
  features:
    window_size: 32
    max_sequence_length: 1024
    num_features: 256
    feature_types:
      - name: "binary"
        size: 64
      - name: "categorical"
        size: 32
        embedding_dim: 16
      - name: "numerical"
        size: 160
        normalization: "standard"
    
  # Model checkpointing
  checkpointing:
    save_best: true
    save_frequency: 10
    max_checkpoints: 5
    checkpoint_dir: "c:/bitcoin_recovery/31k/expert/bitcoin_recovery_ai/models/checkpoints"
    
  # Validation
  validation:
    validation_frequency: 1
    validation_split: 0.2
    metrics:
      - "accuracy"
      - "precision"
      - "recall"
      - "f1"
    
  # Inference
  inference:
    batch_size: 16
    num_workers: 4
    timeout: 300
    fallback_strategies: true
    cache_predictions: true
    
  # Hardware
  hardware:
    device: "cuda"
    num_workers: 4
    pin_memory: true
    cuda_deterministic: true
    benchmark_mode: false